AddressAndPortsScreen.ManagerAddress=MACHINE_IP
AddressAndPortsScreen.NewNode=True
UpgradeVerificationScreen.Overwrite=False
LicenseScreen.License.-1=DX-BZ9W-NNMRS-KKGTN-DM8P4-KCZRM-PZNYR
DatabaseScreen.DatabaseType=PostgreSQL
DatabaseScreen.Hostname=127.0.0.1:5432
DatabaseScreen.Transport=TCP
DatabaseScreen.DatabaseName=dsm
DatabaseScreen.Username=postgres
DatabaseScreen.Password=pgsql
AddressAndPortsScreen.ManagerPort=4119
AddressAndPortsScreen.HeartbeatPort=4120
CredentialsScreen.Administrator.Username=masteradmin
CredentialsScreen.Administrator.Password=AppleTree#1975!
CredentialsScreen.UseStrongPasswords=False
SecurityUpdateScreen.UpdateComponents=True
SecurityUpdateScreen.Proxy=False
SecurityUpdateScreen.ProxyType=""
SecurityUpdateScreen.ProxyAddress=""
SecurityUpdateScreen.ProxyPort=""
SecurityUpdateScreen.ProxyAuthentication="False"
SecurityUpdateScreen.ProxyUsername=""
SecurityUpdateScreen.ProxyPassword=""
SoftwareUpdateScreen.UpdateSoftware=True
SoftwareUpdateScreen.Proxy=False
SoftwareUpdateScreen.ProxyType=""
SoftwareUpdateScreen.ProxyAddress=""
SoftwareUpdateScreen.ProxyPort=""
SoftwareUpdateScreen.ProxyAuthentication="False"
PreCheckSummaryScreen.OperationKey="416d3fb7-f343-42ad-8087-eb7217226f37"
SoftwareUpdateScreen.ProxyUsername=""
SoftwareUpdateScreen.ProxyPassword=""
SoftwareUpdateScreen.ProxyAuthentication="False"
RelayScreen.Install=True
SmartProtectionNetworkScreen.EnableFeedback=False