locals {
	timestamp = formatdate("YYYYMMDDhhmmss", timestamp())
	security_group_name = "${var.tag_securitygroup_name}_${local.timestamp}"
	dsm_machine_name = "${var.tag_dsm_name}_${local.timestamp}"
	dsm_windows_machine_name = "${var.tag_dsm_windows_name}_${local.timestamp}"
	dsa_windows_machine_name = "${var.tag_dsa_windows_name}_${local.timestamp}"
	dsa_windows_machine_2_name = "${var.tag_dsa_windows_2_name}_${local.timestamp}"
	dsa_amazon1_machine_name = "${var.tag_dsa_amazon1_name}_${local.timestamp}"
	dsa_amazon2_machine_name = "${var.tag_dsa_amazon2_name}_${local.timestamp}"
	dsa_rhel_machine_name = "${var.tag_dsa_rhel_name}_${local.timestamp}"
	dsa_ubuntu_machine_name = "${var.tag_dsa_ubuntu_name}_${local.timestamp}"
	dsa_solaris_machine_name = "${var.tag_dsa_solaris_name}_${local.timestamp}"
	dsa_cloudlinux8_machine_name = "${var.tag_dsa_cloudlinux8_name}_${local.timestamp}"
	dsa_cloudlinux7_machine_name = "${var.tag_dsa_cloudlinux7_name}_${local.timestamp}"
	dsa_oraclelinux7_machine_name = "${var.tag_dsa_oraclelinux7_name}_${local.timestamp}"
	dsa_oraclelinux8_machine_name = "${var.tag_dsa_oraclelinux8_name}_${local.timestamp}"
	dsa_debian9_machine_name = "${var.tag_dsa_debian9_name}_${local.timestamp}"
	dsa_debian10_machine_name = "${var.tag_dsa_debian10_name}_${local.timestamp}"
	dsa_centos8_machine_name = "${var.tag_dsa_centos8_name}_${local.timestamp}"
	dsa_centos7_machine_name = "${var.tag_dsa_centos7_name}_${local.timestamp}"
}
